// Suggested code may be subject to a license. Learn more: ~LicenseLog:3586193686.
"use-client";
import type React from "react"

import { type Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/theme-provider";

import "./globals.css";
import Header from "@/components/header";
import { Toaster } from "@/components/ui/sonner";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body suppressHydrationWarning={true}>
          {/* <ThemeProvider >*/}
            <div className="flex min-h-screen flex-col ">
              <Header />
              <main className="flex-1">{children}</main>
            <Footer/>
            </div>
            <Toaster/>
          {/* </ThemeProvider> */}
        </body>
      </html>
    </ClerkProvider>
  );
}
